//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTX_STORE_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        public int MADH { get; set; }
        public Nullable<int> MAKH { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<System.DateTime> NGAYGIAO { get; set; }
        public string TINHTRANG { get; set; }
    
        public virtual CHITIETDONHANG CHITIETDONHANG { get; set; }
        public virtual KHACH KHACH { get; set; }
    }
}
