//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTX_STORE_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIOHANG()
        {
            this.CT_GIOHANG = new HashSet<CT_GIOHANG>();
        }
    
        public int MAGH { get; set; }
        public Nullable<int> MAKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_GIOHANG> CT_GIOHANG { get; set; }
        public virtual KHACH KHACH { get; set; }
    }
}
