//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTX_STORE_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
            this.CT_GIOHANG = new HashSet<CT_GIOHANG>();
        }
    
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<int> BAOHANH { get; set; }
        public string IMGSP1 { get; set; }
        public string IMGSP2 { get; set; }
        public string IMGSP3 { get; set; }
        public string MIEUTA { get; set; }
        public Nullable<double> GIA { get; set; }
        public Nullable<int> SOLUONGSP { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<int> MANSX { get; set; }
        public Nullable<int> MALOAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_GIOHANG> CT_GIOHANG { get; set; }
        public virtual HANGSX HANGSX { get; set; }
        public virtual LOAISP LOAISP { get; set; }
    }
}
